name: pda
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.12.0 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.1
  flutter: 
    sdk: flutter
  flutter_localizations: 
    sdk: flutter
  flutter_launcher_icons: ^0.9.2
  shared_preferences: ^2.0.11
  crypto: ^3.0.1
  convert: ^3.0.1
  encrypt: ^5.0.1
  decimal: ^2.1.0
  pull_to_refresh: ^2.0.0
  intl: ^0.17.0
  signalr_netcore: ^1.2.3+1
  url_launcher: ^6.1.1

dev_dependencies: 
  flutter_lints: ^1.0.0
  lints: 1.0.1
  flutter_test: 
    sdk: flutter

flutter_icons:
  android: true
  image_path: "assets/icon/icon.png"

flutter: 
  uses-material-design: true

